### ISSUE TITLE
Annotation issues

### ISSUE THREAD

**Issue by RRuschel** [Jingkang50/OpenPVSG#11]
Hello,

Thanks for the great work on putting this dataset together!
However, I noticed that some relations for VidOR annotations, for example "squatting on" are not listed at the top of the "relations" key at the top of the json. Was this done by accident or you decided to remove those relations since they have very few samples?

Also I noticed some cases where the annotations refers to an object that is not annotated on the current frame, is that also by accident or something that was expected for a reason?

Thanks!

**Comment by Jingkang50** [comment]
Thank you for using our work! 
Yes, we decided to remove those relations from relation classes since they have very few samples. Although they were annotated by annotators, we ignore them in model training and inference.

For triplets that contain objects that are not annotated on the current frame, it was also by design, since it is a video dataset, and some relations should still hold even though the subject and object are outside the frame.

Hope it helps!

**Comment by RRuschel** [comment]
Sounds great, thanks!
